global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'verification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['verification-service:8080']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8081']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']